hooks:
  - &base
    language: python
    types: [python]
    require_serial: true
    exclude: ^migrations/versions
  - &flake8
    id: flake8
    name: flake8
    entry: flake8
    <<: *base
  - &isort
    id: isort
    name: isort
    entry: isort
    <<: *base

repos:
  - repo: local
    hooks:
      - <<: *flake8
      - <<: *isort
        args: ['--check-only', '--diff']

